Today we will focus on building linear models to analyze a given variable. The methods used differ depending on the type of variable you are using to describe the data (the variable used to describe is called the independent variable). We will start with analyzing a quantitative variable using a qualitative one.


For that we use the method known as Analysis of Variance (ANOVA for short). The idea here is simple. While obviously we cannot find a linear equation between the quantitative data and qualitative data because of discrete nature of the latter (and probable lack of natural order on this variable), we still can check how the variable in question bechaves when grouped by the qualitative one. One we have this grouping the null hypothesis becomes that the mean values between the groups are roughly the same (the alternative is that for some this is not true). To test if this hypothesis holds true we have to create a linear model between the variables. For that we use the function lm(). When analyzing against only one variable (which is called one way analysis) we put the formule in the for main_valiable~independent_variable to this function. On this linear model we can use the the function anova() (or the aov() function, there is some small difference in the way the results are presented but it does more less the same) to check if the null hypothesis holds any ground. If there is a reason to reject this hypothesis there will be a number of * near the p-value (the more * the more significant difference.)


 The file App.csv contains data about the cost of appendectomy in hospitals in different areas in the USA. Preform a test to decide whether the difference between the costs depending on the regions is significant.

In [1]:
A <- read.csv2("Data/App.csv")
A

   cost region
1  3821 rural
2  3981 rural
3  3931 rural
4  5498 regional
5  5582 rural
6  6046 regional
7  4257 metropolitan
8  4591 rural
9  4775 regional
10 6163 metropolitan
11 3840 rural
12 4053 rural
13 4844 regional
14 6266 metropolitan
15 4026 regional
16 2478 metropolitan
17 4347 regional
18 5104 rural
19 4673 rural
20 6389 regional
21 3935 rural
22 2659 regional
23 4072 regional
24 5442 rural
25 5159 rural
26 2861 rural
27 5012 rural
28 2251 metropolitan
29 3441 regional
30 5143 metropolitan
31 3677 regional
32 4891 rural
33 4887 rural
34 5299 regional
35 3597 rural
36 4210 rural
37 4532 metropolitan
38 4212 metropolitan
39 3822 regional
40 3556 metropolitan
41 4175 rural
42 3628 rural
43 4519 rural
44 5693 rural
45 8000 rural
46 5119 regional
47 3362 metropolitan
48 4508 metropolitan
49 6439 rural
50 4071 regional
51 3366 metropolitan
52 5506 metropolitan
53 3987 rural
54 3997 rural
55 2671 rural
56 4683 rural
57 4950 metropolitan
58 4336 regional
59 4896 rural

In [2]:
model <- aov(cost ~ region, data = A)

In [3]:
shapiro.test(residuals(model))

	Shapiro-Wilk normality test

data:  residuals(model)
W = 0.97015, p-value = 0.1555

In [6]:
install.packages("car")

Installing package into ‘/home/natalia/R/x86_64-pc-linux-gnu-library/4.3’
(as ‘lib’ is unspecified)

also installing the dependencies ‘fracdiff’, ‘lmtest’, ‘timeDate’, ‘urca’, ‘zoo’, ‘RcppArmadillo’, ‘generics’, ‘tidyr’, ‘tidyselect’, ‘cowplot’, ‘Deriv’, ‘forecast’, ‘modelr’, ‘microbenchmark’, ‘rbibutils’, ‘broom’, ‘dplyr’, ‘numDeriv’, ‘doBy’, ‘SparseM’, ‘MatrixModels’, ‘Rdpack’, ‘minqa’, ‘nloptr’, ‘reformulas’, ‘RcppEigen’, ‘carData’, ‘abind’, ‘pbkrtest’, ‘quantreg’, ‘lme4’


Warning message in install.packages("car"):
“installation of package ‘nloptr’ had non-zero exit status”
Warning message in install.packages("car"):
“installation of package ‘forecast’ had non-zero exit status”
Warning message in install.packages("car"):
“installation of package ‘lme4’ had non-zero exit status”
Warning message in install.packages("car"):
“installation of package ‘doBy’ had non-zero exit status”
Warning message in install.packages("car"):
“installation of package ‘pbkrtest’ had non-zero exit status”
Warning message in install.packages("car"):
“installation of package ‘car’ had non-zero exit status”

In [5]:
library(car)
leveneTest(cost ~ region, data = A)

ERROR: Error in library(car): there is no package called ‘car’

In [ ]:
summary(model)

            Df   Sum Sq Mean Sq F value Pr(>F)
region       2   545154  272577   0.233  0.793
Residuals   56 65593438 1171311

In [ ]:
TukeyHSD(model)

  Tukey multiple comparisons of means
    95% family-wise confidence level

Fit: aov(formula = cost ~ region, data = A)

$region
                           diff       lwr       upr     p adj
regional-metropolitan 201.31250 -752.2530 1154.8780 0.8676289
rural-metropolitan    235.62069 -612.3584 1083.5997 0.7823808
rural-regional         34.30819 -777.1407  845.7571 0.9943043

The file Famn.csv contains data about the average cost for groceries per family member, depending on the number of family members. Preform a test to decide whether the difference between the costs depending on the number of member of the family is significant. Remember to transform the number column to a factor type of column.

In [ ]:
B <- read.csv2("Data/Famn.csv")
B$number <- as.factor(B$number)
B

   number cost
1  2      78
2  2      85
3  1      88
4  3      76
5  4      72
6  3      74
7  2      79
8  4      69
9  1      79
10 3      75
11 5      68
12 2      82
13 2      78
14 3      72
15 4      76
16 1      90
17 2      84
18 6      67
19 3      77
20 2      79

In [ ]:
model <- aov(cost ~ number, data = B)

In [ ]:
shapiro.test(residuals(model))

	Shapiro-Wilk normality test

data:  residuals(model)
W = 0.96445, p-value = 0.6359

In [ ]:
leveneTest(cost ~ number, data = B)

      Df F value   Pr(>F)
group  5 0.5658322 0.724911
      14        NA       NA

In [ ]:
summary(model)

            Df Sum Sq Mean Sq F value   Pr(>F)
number       5  589.2   117.8   10.34 0.000261 ***
Residuals   14  159.6    11.4
---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1

If we found that there is a reason to reject the null hypothesis that does not mean that all of the mean values differ. To find out which pairs of groups have different means we conduct what is called a post-hoc test. In our case we will go with Tukey's HSD test (short for Honestly Significant Differences). For that we put the model into the TukeyHSD() function. It will compare the groups pairwise and by the p-values we can see where the differences are significant.

Perform a TukeyHSD test on the aov data from the previous two exercises.

In [ ]:
TukeyHSD(model)

  Tukey multiple comparisons of means
    95% family-wise confidence level

Fit: aov(formula = cost ~ number, data = B)

$number
          diff       lwr        upr     p adj
2-1  -4.952381 -12.59350  2.6887398 0.3289612
3-1 -10.866667 -18.95327 -2.7800646 0.0063228
4-1 -13.333333 -22.37443 -4.2922374 0.0028909
5-1 -17.666667 -30.45271 -4.8806261 0.0050344
6-1 -18.666667 -31.45271 -5.8806261 0.0031566
3-2  -5.914286 -12.39799  0.5694202 0.0832657
4-2  -8.380952 -16.02207 -0.7398317 0.0280908
5-2 -12.714286 -24.55186 -0.8767124 0.0321983
6-2 -13.714286 -25.55186 -1.8767124 0.0193676
4-3  -2.466667 -10.55327  5.6199354 0.9102320
5-3  -6.800000 -18.92990  5.3299031 0.4742203
6-3  -7.800000 -19.92990  4.3299031 0.3365535
5-4  -4.333333 -17.11937  8.4527072 0.8687041
6-4  -5.333333 -18.11937  7.4527072 0.7442017
6-5  -1.000000 -16.65964 14.6596376 0.9999302

Of course we can want to group our data by more than one qualitative variable in one time. We could make a one way ANOVA for each of those variables but that way we do not catch any of the dependencies between the qualitative variables. So we conduct what we call multi way ANOVA (two way if we only use two variables). The main difference is how we provide the formula for the lm() function. It is in the form main_variable~independent_variable1(special symbol)independent_variable2, where the (special symbol) is chosen depending on what relation we want to check between the two variables. So we use '+' if we assume no interaction between those variables ':' if we want to focus only on the interaction and '*' if we want to do both.

The file Pri.csv contains data about the dependence between the price of apartments and several parameters in 3 different districts. Analyse the variance one way against the district and the type of building, and then conduct a twoway analysis against both of those variables at the same time, without assuming interaction.

In [ ]:
C <- read.csv2("Data/Pri.csv")
C$district <- as.factor(C$district)
C$type <- as.factor(C$type)
C$price <- as.numeric(C$price)
C

    price     rooms area district    type
1   226298.17 4     76.4 Krzyki      new high
2   128121.35 1     19.4 Biskupin    new high
3   118333.42 1     21.5 Srodmiescie new high
4   202064.16 4     65.2 Srodmiescie new high
5   130303.00 1     21.4 Krzyki      new high
6   156241.89 2     35.8 Biskupin    new high
7   186732.01 2     41.1 Biskupin    old
8    98925.66 1     18.1 Krzyki      old
9   193186.71 3     54.6 Srodmiescie new high
10  116306.58 1     18.9 Krzyki      new high
11  200661.77 3     60.4 Biskupin    old
12  120513.56 1     17.0 Srodmiescie old
13  165908.86 3     46.2 Krzyki      old
14  149856.60 2     37.9 Krzyki      old
15  136640.17 2     30.6 Srodmiescie old
16  143616.79 2     34.8 Krzyki      new high
17  146439.27 2     29.8 Biskupin    new high
18  158608.89 2     35.5 Krzyki      new low
19  204529.65 3     61.3 Srodmiescie old
20  186816.07 4     63.2 Krzyki      old
21  172528.26 3     45.1 Biskupin    new high
22  245845.93 4     80.3 Srodmiescie new low
23  123690.76 1     19.3 Biskupin    new high
24  149943.62 2     32.4 Srodmiescie old
25  149948.18 2     32.4 Srodmiescie old
26  214461.62 3     49.6 Biskupin    new low
27  199465.03 3     44.0 Biskupin    old
28   93055.36 1     17.9 Krzyki      new high
29  140947.96 2     35.6 Krzyki      new high
30  214379.62 3     64.7 Krzyki      new high
⋮   ⋮         ⋮     ⋮    ⋮           ⋮
171 115372.91 1     19.8 Krzyki      new low
172 214730.38 3     61.4 Biskupin    new high
173 203659.76 3     50.3 Biskupin    new high
174 124882.95 1     21.8 Srodmiescie new high
175 284918.48 4     87.5 Biskupin    old
176 202351.98 3     52.3 Biskupin    old
177 185705.46 3     49.7 Krzyki      new low
178 217603.33 3     59.3 Srodmiescie new low
179 126914.76 1     18.7 Biskupin    new high
180 223571.58 3     65.2 Biskupin    old
181 201396.16 3     52.9 Srodmiescie new high
182 160994.25 2     34.2 Srodmiescie new low
183  96257.94 1     18.8 Krzyki      old
184 188118.00 3     43.8 Biskupin    new low
185 137932.35 1     19.7 Biskupin    new low
186 192672.25 4     61.5 Krzyki      old
187 159952.91 2     31.2 Biskupin    old
188 135116.05 1     18.1 Biskupin    new high
189 179641.33 2     36.0 Biskupin    old
190 249970.46 4     74.8 Biskupin    new low
191 138568.41 2     32.9 Krzyki      new high
192 142365.84 1     19.6 Biskupin    new low
193 156655.41 2     37.3 Biskupin    old
194 219932.64 4     69.3 Krzyki      old
195 128388.52 1     21.2 Srodmiescie new high
196 146754.24 2     41.9 Krzyki      new low
197 170525.14 4     53.3 Krzyki      new high
198 215650.43 4     82.8 Krzyki      old
199 168853.50 2     40.1 Krzyki      new low
200 175606.84 3     51.3 Biskupin    new high

In [ ]:
model1 <- aov(price ~ district, data = C)

In [ ]:
model2 <- aov(price ~ type, data = C)

In [ ]:
model3 <- aov(price ~ district + type, data = C)

In [ ]:
shapiro.test(residuals(model1))

	Shapiro-Wilk normality test

data:  residuals(model1)
W = 0.98389, p-value = 0.02178

In [ ]:
shapiro.test(residuals(model2))

	Shapiro-Wilk normality test

data:  residuals(model2)
W = 0.98653, p-value = 0.05416

In [ ]:
shapiro.test(residuals(model3))

	Shapiro-Wilk normality test

data:  residuals(model3)
W = 0.97975, p-value = 0.005475

In [ ]:
leveneTest(price ~ district, data = C)

      Df  F value  Pr(>F)
group   2 0.693399 0.5010899
      197       NA        NA

In [ ]:
leveneTest(price ~ type, data = C)

      Df  F value   Pr(>F)
group   2 0.1698176 0.8439421
      197        NA        NA

In [ ]:
leveneTest(price ~ district * type, data = C)

      Df  F value   Pr(>F)
group   8 0.2833351 0.9708636
      191        NA        NA

In [ ]:
summary(model1)

             Df    Sum Sq   Mean Sq F value  Pr(>F)
district      2 1.800e+10 8.998e+09   5.046 0.00729 **
Residuals   197 3.513e+11 1.783e+09
---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1

In [ ]:
summary(model2)

             Df    Sum Sq   Mean Sq F value  Pr(>F)
type          2 2.277e+10 1.139e+10   6.472 0.00189 **
Residuals   197 3.465e+11 1.759e+09
---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1

In [ ]:
summary(model3)

             Df    Sum Sq   Mean Sq F value  Pr(>F)
district      2 1.800e+10 8.998e+09   5.340 0.00552 **
type          2 2.272e+10 1.136e+10   6.741 0.00148 **
Residuals   195 3.286e+11 1.685e+09
---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1

Things get a little simpler if the variable we are using to describe the date we are interested in is of a quantitative kind. In such a case we can assume that the data can be described as a linear function of the variable we are using (whether this is reasonable highly depends on the covariance between the variables). Such an approach we call linear regression and the lm() function will straight out calculate the coefficients of the most probable linear function to describe this relation. They will be given in the model under the value 'coefficients'.

The file Per.csv contains the heights of baby brothers and sisters in different families. Construct a linear regression model of the height of boys against girls. Plot the model.

In [ ]:
library(e1071)
Per <- read.csv2('Data/Per.csv')
Per_complete <- na.omit(Per)

model_per <- lm(brother ~ sister, data = Per_complete)
summary(model_per)

plot(Per_complete$sister, Per_complete$brother,
     xlab = 'sister', ylab = 'brother',
     main = 'brother ~ sister')
abline(model_per, col = 'red')

If we have the formula for the regression line we can use it to predict the value of the data we are interested in by simply supplying the values of the independent variable to the formula for the regression line.

The file Books.csv contains the data of the relation between numbers of books read and the final spelling scores for third graders. Use it to predict the score for someone who read: 3 books, 7 books, and 49 books.

In [ ]:
Books <- read.csv2('Data/Books.csv')
model_books <- lm(spelling ~ book, data = Books)
summary(model_books)

predict(model_books, newdata = data.frame(book = c(3, 7, 49)))

As in the case of ANOVA we can test our data against multiple independent quantitative variables. The way we provide the formula is similar to what we did in two way ANOVA.

Use the data from Pri.csv for this exercise to create a regression model for price against the area of the apartment, the number of rooms separately, and against both the area and number of rooms.

In [ ]:
model_area  <- lm(price ~ area,         data = C)
model_rooms <- lm(price ~ rooms,        data = C)
model_both  <- lm(price ~ area + rooms, data = C)

summary(model_area)
summary(model_rooms)
summary(model_both)

Finally it is somewhat obvious that not always we know which variables are significant to describing the data we are interested in. We also do not want to check each combination of variables by ourselves. Luckily we have the function step() that can check that for us. This function has an important parameter called 'direction'. If it is forward than the function will try to add new parameters if they are useful to the model so in this case we want to start with as small model as possible. If backward it will try to subtract independent variables, checking if the loss of information is significant, so we want to start with a model that has all of the variables that we want to check.

Read the documentation to the step() function and use it to decide if the model with both area and number of rooms are necessary for a good model of price.

In [ ]:
step(model_both, direction = 'backward')