Todays lab is focused around file manipulation and a little bit around generating random numbers. File manipulation will be centered around reading and writing in csv files, as most data we work with in available in this format.

When working in R we always have a directory called "working directory" which is the base from we start our operations. You can check your working directory using the `getwd()` function, and you can change it using the `setwd(path)` function. We can create files using `file.create(path)`, and remove them with `file.remove(path)`.Other functions used for file manipulation `file.rename(from,to)` which renames a file from one name to another, `file.append(file1,file2)` which tries to append file2 at the end of file one, or `file.copy(from,to, overwrite = recursive, recursive = FALSE,copy.mode = TRUE, copy.date = FALSE)`.

Exercise 1. Create a new file named Noise.txt. Use the function list.files() to load a vector of all file paths
from your working directory to a variable Names. Use file.exists() on Names to confirm that all of the files are
in the working directory. Remove Noise.txt using the proper command. Check the result of using file.exists() on
Names.

In [1]:
getwd()

[1] "/home/natalia/Repos/SFIS"

In [2]:
file.create('Data/Noise.txt')

[1] TRUE

In [3]:
list.files()

 [1] "Data"
 [2] "Project1"
 [3] "SfIS_III_Files_and_RNG.ipynb"
 [4] "SfIS_IV_Basic_data_preprocessing_and_presentation.ipynb"
 [5] "SfIS_IX_Linear_model.ipynb"
 [6] "SfIS_V_Drawing_graphs_lattice.ipynb"
 [7] "SfIS_VI_Drawing_graphs_ggplot2.ipynb"
 [8] "SfIS_VII_Estimations.ipynb"
 [9] "SfIS_VIII_Testing_hypothesis.ipynb"
[10] "SfIS_X_Non_linear_models.ipynb"

In [4]:
file.exists('Data/Noise.txt')

[1] TRUE

In [5]:
file.remove('Data/Noise.txt')

[1] TRUE

In [6]:
file.exists('Data/Noise.txt')

[1] FALSE

For reading and writing in csv files we will use the `read.csv2(file)` and `write.csv2(data_frame, file)` functions where file is the name of the file written in "". Please read the full documentation for these functions, for the full view of the arguments you have inside. There are different conventions  with separation markers in csv files around the world, csv2 is for working with files from central Europe among others. A data frame is a data structure in R which we will mostly use in R form now on. We will go more in-depth on it next time, for now just think of it as an 2-dimensional table with (possibly) named rows and columns, where each column is of the same data type.

Exercise 2. The file Books.csv contains the data of the relation between numbers of books read and the final
spelling scores for third graders. Copy the file Books.csv to Books2.csv and append Books.csv to the new file.
Load Books2.csv to a variable B. Check the content of B. Correct this data frame, so it has numerical values
(apart of the variables names).

In [7]:
file.copy('Data/Books.csv', 'Data/Books2.csv')
file.append('Data/Books2.csv', 'Data/Books.csv')
B = read.csv2('Data/Books2.csv')
B = B[B[,1] != names(B)[1], ] # tbh i couldn't figure it out and i asked gpt :(
B[] = lapply(B, as.numeric)
B

[1] TRUE

[1] TRUE

   book spelling
1  27   85
2  11   81
3  32   98
4   5   61
5  17   92
6   0   36
7   8   59
8  15   84
9  24   90
10  6   70
11  4   72
12 23   95
13 41   99
14  7   78
15  2   58
16 19   87
17 13   80
19 27   85
20 11   81
21 32   98
22  5   61
23 17   92
24  0   36
25  8   59
26 15   84
27 24   90
28  6   70
29  4   72
30 23   95
31 41   99
32  7   78
33  2   58
34 19   87
35 13   80



Exercise 3. Load the file Books.csv to a variable B. Write B to the file B3.csv using the write.csv() command.
Try loading B3.csv using read.csv2(). What is the result?

In [8]:
B = read.csv2('Data/Books.csv')
write.csv(B, 'Data/B3.csv') # comma separated
B3 = read.csv2('Data/B3.csv')
B3

   X.book.spelling
1  1,27,85
2  2,11,81
3  3,32,98
4  4,5,61
5  5,17,92
6  6,0,36
7  7,8,59
8  8,15,84
9  9,24,90
10 10,6,70
11 11,4,72
12 12,23,95
13 13,41,99
14 14,7,78
15 15,2,58
16 16,19,87
17 17,13,80


Exercise 4. The file Life.csv contains data of US life expectancy sorted by decades. Load the file to a variable
x1 and write it to a file L1.csv using write.csv2() without adding the parameter row.names=FALSE. Load the
file L1.csv to x1, and repeat the writing process. Now, load Life.csv to a variable x2 and write it to a file L2.csv
using write.csv2() and add the parameter row.names=FALSE. Load the file L2.csv to x2, and repeat the writing
process. Compare the data in L1.csv and L2.csv.




Exercise 5. Append L1.csv to L2.csv. Try to load the result using read.csv2() without changing the fill parameter.
Now load the file with the parameter fill = FALSE. Check the result.

In [9]:
x1 = read.csv2('Data/Life.csv')
write.csv2(x1, 'Data/L1.csv')
x1 = read.csv2('Data/L1.csv')
write.csv2(x1, 'Data/L1.csv')
x2 = read.csv2('Data/Life.csv')
write.csv2(x2, 'Data/L2.csv', row.names=FALSE)
x2 = read.csv2('Data/L2.csv')
write.csv2(x2, 'Data/L2.csv', row.names=FALSE)

In [10]:
L1 = read.csv2('Data/L1.csv')
L1

  X.1 X year men  women
1 1   1 1920 53.6 54.6
2 2   2 1930 58.1 61.6
3 3   3 1940 60.8 65.2
4 4   4 1950 65.6 71.1
5 5   5 1960 66.6 73.1
6 6   6 1970 67.1 74.7
7 7   7 1980 70.0 77.5
8 8   8 1990 71.8 78.8

In [11]:
L2 = read.csv2('Data/L2.csv')
L2

  year men  women
1 1920 53.6 54.6
2 1930 58.1 61.6
3 1940 60.8 65.2
4 1950 65.6 71.1
5 1960 66.6 73.1
6 1970 67.1 74.7
7 1980 70.0 77.5
8 1990 71.8 78.8

In [ ]:
file.append('Data/L2.csv', 'Data/L1.csv')
L3 = read.csv2('Data/L2.csv', fill = FALSE)
L3 # not sure it it's intended that it doesn't work

[1] TRUE

ERROR: Error in scan(file = file, what = what, sep = sep, quote = quote, dec = dec, : line 9 did not have 3 elements

Generating pseudorandom numbers is often important were statistics are involved. In R several algoritms to generate those numbers are available and you have always two generators ready when you call a function that uses randomness (one generator for the uniform distribution, one for the normal distribution). You can use `RNGkind(uniform algo, normal algo)` to change the algorithms, and you will get the names of the previously used as output. As you may know, when generating pseudorandom numbers you use a seed with the values given to the algorithm. It is kept under the variable `.Random.seed`. You can set the starting point of the seed using the function `set.seed(value)`.



Exercise 6. Check the names of the random number generators set on your session. Display the current seed.
Change your generators to ”Super-Duper” and ”Box-Muller” for uniform and normal distribution respectively.
Display the seed of the new generator.

In [13]:
RNGkind()

[1] "Mersenne-Twister" "Inversion"        "Rejection"

In [21]:
.Random.seed

[1]      10202 2053628949  802928083

In [19]:
RNGkind('Super-Duper', 'Box-Muller')
RNGkind()

[1] "Super-Duper" "Box-Muller"  "Rejection"

In [20]:
.Random.seed

[1]      10202 2053628949  802928083

There are several functions for generating random values and other useful information from known distributions. The have a common naming convention: $[prefix][name of distribution]$ where prefix is one of the four: r, p, d, q, and the name is usually a four letter shortcut. r- is for generating random numbers from the distribution, p- gives the values from the cumulative distribution function, d gives  the value of density in that point for contunous distributions and the probability of given values for discreate distributions, and q is used to find quartiles. norm is for normal distribution, unif for uniform and chisq for chi-squared.



Exercise 7. Use set.seed(5) to create a new random seed. Create a vector of 7 random numbers take from
the normal distribution with mean 2 and standard deviation 1, then create a second vector with the same
parameters. Use set.seed(5) and create another vector with the same parameters. Now set.seed(6) and create
another vector with the same parameters. Compare the results.

In [22]:
set.seed(5)
v1 = rnorm(7, mean = 2, sd = 1)

v2 = rnorm(7, mean = 2, sd = 1)

set.seed(5)
v3 = rnorm(7, mean = 2, sd = 1)

set.seed(6)
v4 = rnorm(7, mean = 2, sd = 1)

In [23]:
v1

[1] 0.5849085 1.0608210 2.1381849 2.1876450 2.2859185 3.0562857 2.6901459

In [24]:
v2

[1] 0.4536370 1.4668757 0.5557903 2.3345957 3.6514184 0.2850535 1.9548668

In [25]:
v3

[1] 0.5849085 1.0608210 2.1381849 2.1876450 2.2859185 3.0562857 2.6901459

In [26]:
v4

[1] 2.81987813 0.05544571 4.13332988 0.39404306 3.50273383 1.18049142 1.76929998



Exercise 8. Use the proper function with prefix p to find the probability of a random value being less then -1,
0.5, 2, 5 for the following distributions: uniform distribution with min=0, max=3; uniform distribution with
min=-3 and max =6; normal distribution with mean = 0 and standard deviation = 4; chi-square distribution
with 5 degrees of freedom.

In [27]:
x = c(-1, 0.5, 2, 5)
x

[1] -1.0  0.5  2.0  5.0

In [28]:
punif(x, min = 0, max = 3)

[1] 0.0000000 0.1666667 0.6666667 1.0000000

In [29]:
punif(x, min = -3, max = 6)

[1] 0.2222222 0.3888889 0.5555556 0.8888889

In [30]:
pnorm(x, mean = 0, sd = 4)

[1] 0.4012937 0.5497382 0.6914625 0.8943502

In [31]:
pchisq(x, df = 5)

[1] 0.000000000 0.007876707 0.150854964 0.584119813



Exercise 9. Use the proper prefixes p and d to find the probability of having exactly 4 successes in a binomial
test of size 10 and probability of success 0.6, having exactly 1 success, having at most 4 successes, and having
at least 9 successes.

In [32]:
dbinom(4, size = 10, prob = 0.6)

[1] 0.1114767

In [33]:
dbinom(1, size = 10, prob = 0.6)

[1] 0.001572864

In [34]:
pbinom(4, size = 10, prob = 0.6)

[1] 0.1662386

In [35]:
1 - pbinom(8, size = 10, prob = 0.6)

[1] 0.0463574





Exercise 10. Compare the values of every tenth quartile, using a vector of values from 0.1 to 0.9 and the prefix
q for the following distributions: normal with mean 3 and standard deviation 2; uniform in the range from -3
to 3; t-Student for 6 degrees of freedom.
1

In [36]:
p = seq(0.1, 0.9, 0.1)
p

[1] 0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9

In [37]:
qnorm(p, mean = 3, sd = 2)

[1] 0.4368969 1.3167575 1.9511990 2.4933058 3.0000000 3.5066942 4.0488010
[8] 4.6832425 5.5631031

In [38]:
qunif(p, min = -3, max = 3)

[1] -2.4 -1.8 -1.2 -0.6  0.0  0.6  1.2  1.8  2.4

In [39]:
qt(p, df = 6)

[1] -1.4397557 -0.9057033 -0.5533809 -0.2648345  0.0000000  0.2648345  0.5533809
[8]  0.9057033  1.4397557